### PR TITLE
Suggestion for https://github.com/scikit-learn/scikit-learn/pull/16084

### PR DESCRIPTION
**Pull request by thomasjpfan**
I was thinking of this.

CC: @jnothman

### CODE REVIEW

**Comment by jnothman** [comment]
Nice! Will look a bit more later. Thanks

**Review by jnothman — COMMENTED** [review]
I like this, but the control flow becomes quite hard to read, and it may be hard for the reader to understand why the postprocessing should be outside of `parse_arff` (so that could deserve a comment).

Do you think we can tweak it so that it looks like:


```py
if as_frame:
    def parse_arff(...):
        ....
        return frame,
    def postprocess(frame):
        ....
        return X, y, nominal_attributes
else:
    def parse_arff(...):
        ....
        return X, y, nominal_attributes
    def postrprocess(X, y, nominal_attributes):
        ....
        return X, y, nominal_attributes

    out = _retry_with_clean_cache(url, data_home)(
        _load_arff_response)(url, data_home,
                return_type=return_type,
                encode_nominal=not as_frame,
                parse_arff=parse_arff)
    X, y, nominal_attributes = postprocess(*out)
    return Bunch(...)
```
?

**Comment by thomasjpfan** [comment]
Updated PR with the approach you suggested

**Review by jnothman — APPROVED** [review]

**Comment by jnothman** [comment]
Thank you

**Pull request merged**
